@echo off
title @root:Starting System 420
color F
echo.
echo          Hack Protocol
echo                420
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  л
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420       
echo  ллллллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллллллллллл
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  лллллллллллллллллллллллллл
ping localhost -n 1 > nul
cls
echo.
echo          Hack Protocol
echo                420
echo  ллллллллллллллллллллллллллл
ping localhost -n 1 > nul
cls
title HACK PROTOCOL 420
color A
echo.
echo             Egor2210 THE BEST!!!
ping localhost -n 2 > nul
cls
echo.
echo лллллллллллллллллллллллллллллллллллллллллллллллллллл
:A
ping localhost -n 0.8 > nul
color A
echo л root@:Hacking Pentagon...             %time% 
echo л root@:Hacking IP Adress ќ%random%%random%       
echo л                               Looading... 
ping localhost -n 3 > nul
echo л root@:COMPLETED                       %time%
echo лллллллллллллллллллллллллллллллллллллллллллллллллллл
echo л root@:Searching VK account...
ping localhost -n 2 > nul
echo л root@:VK account searched
echo л root@:Hacking VK account id%random%      %time%
echo л                               Looading...
ping localhost -n 3 > nul
echo л root@:COMPLETED                       %time%
echo лллллллллллллллллллллллллллллллллллллллллллллллллллл
echo л root@:Downloading  files
echo л                            Downloading...
ping localhost -n 3.5 > nul
echo л root@:COMPLETED                       %time%
echo л root@:Folders downloaded %random%        %time%
ping localhost -n 0.5 > nul
echo л root@:Files  downloaded %random%         %time%
ping localhost -n 0.5 > nul
echo л root@:Files total weight %random%%random%MB  %time%
echo лллллллллллллллллллллллллллллллллллллллллллллллллллл
echo.
echo @##################################################@
echo.
echo лллллллллллллллллллллллллллллллллллллллллллллллллллл
  
goto A